#include "lang.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static LangCode current_lang = LANG_ZH_CN;

static const char* strings[9][STR_COUNT] = {

    // ========== LANG_EN ==========
    {
        "p-adic> ", "expr> ", "Choice (1-6): ",
        "Press Enter to return to menu...", "Goodbye!", "Invalid choice, please enter 1-6", "Exit",
        "p-adic Converter", "==========================",
        "1. Parser Test", "2. Integer p-adic Conversion",
        "3. Rational p-adic Conversion Test", "4. Interactive p-adic Conversion",
        "5. Expression Evaluation to p-adic", "6. Quit",
        "Format:",
        "  1. number p                (e.g. 5 7, 1/3 5)",
        "  2. pow(base, exp) p        (e.g. pow(2,1/2) 5)",
        "  3. sqrt(n) p               (e.g. sqrt(2) 5)",
        "Commands: help, quit, exit, menu, language",
        "Format error. Type 'help' for help.",
        "p must be an integer greater than 1", "Parse error",
        "Format error. Usage: pow(base, exponent) p",
        "Format error. Usage: sqrt(n) p",
        "Only square roots supported (exponent must be 1/2)",
        "Cannot convert base to p-adic", "No square root in Q_%d",
        "Error: please use format 'number p', e.g. 17 5 or 3/4 5",
        "Error: please use format 'expression p', e.g. 3+4*2 5",
        "Expression parse error!",
        "=== Interactive p-adic Conversion (precision: 20) ===",
        "  Integer: 17 5  means 5-adic of 17",
        "  Fraction: 3/4 5  means 5-adic of 3/4",
        "Type 'back' or 'menu' to return",
        "Rational: %d/%d", "p-adic base: %d", "Conversion failed",
        "=== Expression Evaluation to p-adic (precision: 20) ===",
        "Input expression and p, e.g. 3+4*2 5",
        "Expression: %s", "Result: %d/%d",
        "=== p-adic Conversion Test (precision: 20) ===",
        "=== Rational p-adic Conversion Test (precision: 20) ===",
        "Test %d: decimal: %d, p-adic base: %d",
        "Test %d: rational: %d/%d, p-adic base: %d",
        "Computing: sqrt(%d/%d) in %d-adic", "First root:", "Second root:",
        "Returning to interactive mode",
        "Current language: English",
        "Formal representation: (", "Series representation: ",
        "Formal representation: (base >= 36, only series shown)",
        "Square root result (precision: %d digits):",
        "Computing: exp(%d/%d) in %d-adic",
        "Computing: log(%d/%d) in %d-adic",
        "Format error. Usage: exp(x) p",
        "Format error. Usage: log(x) p",
        "exp(x) does not converge: need v_p(x) >= 1 (>=2 if p=2)",
        "log(x) does not converge: need x \xe2\x89\xa1 1 (mod p) (mod 4 if p=2)",
        "Failed to convert expression to p-adic",
        "exp result:",
        "log result:",
        "  4. exp(x) p / log(x) p      (e.g. exp(5) 5, log(1+5) 5)",
        "  5. expression p             (e.g. 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_ZH_CN ==========
    {
        "p-adic> ", "表达式> ", "选择 (1-6): ",
        "按回车键返回主菜单...", "再见！", "无效选择，请输入1-6", "退出",
        "p-adic 转换器", "==========================",
        "1. 语法解析器测试", "2. 整数 p-adic 转换",
        "3. 有理数 p-adic 转换测试", "4. 交互式 p-adic 转换",
        "5. 表达式求值并转换为 p-adic", "6. 退出",
        "格式:",
        "  1. 数 p                 (例如: 5 7, 1/3 5)",
        "  2. pow(base, exp) p    (例如: pow(2,1/2) 5)",
        "  3. sqrt(n) p           (例如: sqrt(2) 5)",
        "命令: help, quit, exit, menu, language",
        "格式错误。输入 'help' 查看帮助。",
        "p必须是大于1的整数", "解析错误",
        "格式错误。使用格式: pow(base, exponent) p",
        "格式错误。使用格式: sqrt(n) p",
        "目前只支持平方根计算 (指数必须为 1/2)",
        "无法将底数转换为 p-adic", "在 Q_%d 中没有平方根",
        "错误: 请输入格式为 '数 p'，例如: 17 5 或 3/4 5",
        "错误: 请输入格式为 '表达式 p'，例如: 3+4*2 5",
        "表达式解析错误！",
        "=== 交互式 p-adic 转换 (精度: 20位) ===",
        "  整数: 17 5 表示17的5-adic表示",
        "  分数: 3/4 5 表示3/4的5-adic表示",
        "输入 'back' 或 'menu' 返回主菜单",
        "有理数: %d/%d", "p-adic基数: %d", "转换失败",
        "=== 表达式求值并转换为 p-adic (精度: 20位) ===",
        "输入表达式和p值，例如: 3+4*2 5",
        "表达式: %s", "求值结果: %d/%d",
        "=== p-adic 转换测试 (精度: 20位) ===",
        "=== 有理数 p-adic 转换测试 (精度: 20位) ===",
        "测试%d: 十进制数: %d, p-adic基数(p): %d",
        "测试%d: 有理数: %d/%d, p-adic基数(p): %d",
        "计算: √(%d/%d) 在 %d-adic 中", "第一个解:", "第二个解:",
        "返回交互模式",
        "当前语言: 简体中文",
        "形式表示: (", "级数表示: ",
        "形式表示: (基数大于等于36，无法用单个字符表示，只显示级数表示)",
        "方根运算结果 (精度: %d位):",
        "计算: exp(%d/%d) 在 %d-adic 中",
        "计算: log(%d/%d) 在 %d-adic 中",
        "格式错误。使用格式: exp(x) p",
        "格式错误。使用格式: log(x) p",
        "exp(x) 在该 p-adic 下不收敛：要求 v_p(x) >= 1 (p=2 时 >= 2)",
        "log(x) 在该 p-adic 下不收敛：要求 x ≡ 1 (mod p)  (p=2 时 mod 4)",
        "表达式转换为 p-adic 失败",
        "exp 计算结果:",
        "log 计算结果:",
        "  4. exp(x) p / log(x) p (例如: exp(5) 5, log(1+5) 5)",
        "  5. 表达式 p            (例如: 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_ZH_TW ==========
    {
        "p-adic> ", "運算式> ", "選擇 (1-6): ",
        "按Enter鍵返回主選單...", "再見！", "無效選擇，請輸入1-6", "退出",
        "p-adic 轉換器", "==========================",
        "1. 語法解析器測試", "2. 整數 p-adic 轉換",
        "3. 有理數 p-adic 轉換測試", "4. 互動式 p-adic 轉換",
        "5. 運算式求值並轉換為 p-adic", "6. 退出",
        "格式:",
        "  1. 數 p                 (例如: 5 7, 1/3 5)",
        "  2. pow(base, exp) p    (例如: pow(2,1/2) 5)",
        "  3. sqrt(n) p           (例如: sqrt(2) 5)",
        "指令: help, quit, exit, menu, language",
        "格式錯誤。輸入 'help' 查看說明。",
        "p必須是大於1的整數", "解析錯誤",
        "格式錯誤。使用格式: pow(base, exponent) p",
        "格式錯誤。使用格式: sqrt(n) p",
        "目前只支援平方根計算 (指數必須為 1/2)",
        "無法將底數轉換為 p-adic", "在 Q_%d 中沒有平方根",
        "錯誤: 請輸入格式為 '數 p'，例如: 17 5 或 3/4 5",
        "錯誤: 請輸入格式為 '運算式 p'，例如: 3+4*2 5",
        "運算式解析錯誤！",
        "=== 互動式 p-adic 轉換 (精度: 20位) ===",
        "  整數: 17 5 表示17的5-adic表示",
        "  分數: 3/4 5 表示3/4的5-adic表示",
        "輸入 'back' 或 'menu' 返回主選單",
        "有理數: %d/%d", "p-adic基數: %d", "轉換失敗",
        "=== 運算式求值並轉換為 p-adic (精度: 20位) ===",
        "輸入運算式和p值，例如: 3+4*2 5",
        "運算式: %s", "求值結果: %d/%d",
        "=== p-adic 轉換測試 (精度: 20位) ===",
        "=== 有理數 p-adic 轉換測試 (精度: 20位) ===",
        "測試%d: 十進制數: %d, p-adic基數(p): %d",
        "測試%d: 有理數: %d/%d, p-adic基數(p): %d",
        "計算: √(%d/%d) 在 %d-adic 中", "第一個解:", "第二個解:",
        "返回互動模式",
        "目前語言: 繁體中文",
        "形式表示: (", "級數表示: ",
        "形式表示: (基數大於等於36，無法用單一字元表示，只顯示級數表示)",
        "方根運算結果 (精度: %d位):",
        "計算: exp(%d/%d) 在 %d-adic 中",
        "計算: log(%d/%d) 在 %d-adic 中",
        "格式錯誤。使用格式: exp(x) p",
        "格式錯誤。使用格式: log(x) p",
        "exp(x) 在該 p-adic 下不收斂：需 v_p(x) >= 1 (p=2 時 >= 2)",
        "log(x) 在該 p-adic 下不收斂：需 x ≡ 1 (mod p)  (p=2 時 mod 4)",
        "運算式轉換為 p-adic 失敗",
        "exp 結果:",
        "log 結果:",
        "  4. exp(x) p / log(x) p (例如: exp(5) 5, log(1+5) 5)",
        "  5. 運算式 p            (例如: 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_JA ==========
    {
        "p-adic> ", "式> ", "選択 (1-6): ",
        "Enterキーを押してメニューに戻る...", "さようなら！", "無効な選択です。1-6を入力してください", "終了",
        "p-adic 変換器", "==========================",
        "1. 構文解析テスト", "2. 整数 p-adic 変換",
        "3. 有理数 p-adic 変換テスト", "4. 対話式 p-adic 変換",
        "5. 式の評価と p-adic 変換", "6. 終了",
        "書式:",
        "  1. 数 p                 (例: 5 7, 1/3 5)",
        "  2. pow(base, exp) p    (例: pow(2,1/2) 5)",
        "  3. sqrt(n) p           (例: sqrt(2) 5)",
        "コマンド: help, quit, exit, menu, language",
        "書式エラー。'help' と入力してヘルプを表示。",
        "p は1より大きい整数でなければなりません", "解析エラー",
        "書式エラー。使用法: pow(base, exponent) p",
        "書式エラー。使用法: sqrt(n) p",
        "現在は平方根のみサポート (指数は 1/2 のみ)",
        "底数を p-adic に変換できません", "Q_%d に平方根が存在しません",
        "エラー: '数 p' の形式で入力してください (例: 17 5 または 3/4 5)",
        "エラー: '式 p' の形式で入力してください (例: 3+4*2 5)",
        "式の解析エラー！",
        "=== 対話式 p-adic 変換 (精度: 20桁) ===",
        "  整数: 17 5  → 17 の 5-adic 表現",
        "  分数: 3/4 5 → 3/4 の 5-adic 表現",
        "'back' または 'menu' でメニューに戻る",
        "有理数: %d/%d", "p-adic 基数: %d", "変換失敗",
        "=== 式の評価と p-adic 変換 (精度: 20桁) ===",
        "式と p の値を入力してください (例: 3+4*2 5)",
        "式: %s", "評価結果: %d/%d",
        "=== p-adic 変換テスト (精度: 20桁) ===",
        "=== 有理数 p-adic 変換テスト (精度: 20桁) ===",
        "テスト%d: 10進数: %d, p-adic 基数: %d",
        "テスト%d: 有理数: %d/%d, p-adic 基数: %d",
        "計算: √(%d/%d) の %d-adic 表現", "第1の解:", "第2の解:",
        "対話モードに戻る",
        "現在の言語: 日本語",
        "形式表現: (", "級数表現: ",
        "形式表現: (基数が36以上のため文字表現不可、級数表現のみ表示)",
        "平方根の結果 (精度: %d桁):",
        "計算中: exp(%d/%d) の %d-adic",
        "計算中: log(%d/%d) の %d-adic",
        "書式エラー。使用法: exp(x) p",
        "書式エラー。使用法: log(x) p",
        "exp(x) は収束しません: v_p(x) >= 1 (p=2 の時 >= 2) が必要",
        "log(x) は収束しません: x ≡ 1 (mod p) (p=2 の時 mod 4) が必要",
        "式の p-adic 変換に失敗",
        "exp 結果:",
        "log 結果:",
        "  4. exp(x) p / log(x) p (例: exp(5) 5, log(1+5) 5)",
        "  5. 式 p                (例: 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_KO ==========
    {
        "p-adic> ", "식> ", "선택 (1-6): ",
        "Enter 키를 눌러 메뉴로 돌아가기...", "안녕히 가세요！", "잘못된 선택입니다. 1-6을 입력하세요", "종료",
        "p-adic 변환기", "==========================",
        "1. 구문 분석기 테스트", "2. 정수 p-adic 변환",
        "3. 유리수 p-adic 변환 테스트", "4. 대화형 p-adic 변환",
        "5. 식 평가 및 p-adic 변환", "6. 종료",
        "형식:",
        "  1. 수 p                 (예: 5 7, 1/3 5)",
        "  2. pow(base, exp) p    (예: pow(2,1/2) 5)",
        "  3. sqrt(n) p           (예: sqrt(2) 5)",
        "명령어: help, quit, exit, menu, language",
        "형식 오류. 'help'를 입력하여 도움말을 확인하세요.",
        "p는 1보다 큰 정수여야 합니다", "파싱 오류",
        "형식 오류. 사용법: pow(base, exponent) p",
        "형식 오류. 사용법: sqrt(n) p",
        "현재 제곱근만 지원됩니다 (지수는 1/2이어야 함)",
        "밑수를 p-adic으로 변환할 수 없습니다", "Q_%d에 제곱근이 없습니다",
        "오류: '수 p' 형식으로 입력하세요 (예: 17 5 또는 3/4 5)",
        "오류: '식 p' 형식으로 입력하세요 (예: 3+4*2 5)",
        "식 파싱 오류!",
        "=== 대화형 p-adic 변환 (정밀도: 20자리) ===",
        "  정수: 17 5  → 17의 5-adic 표현",
        "  분수: 3/4 5 → 3/4의 5-adic 표현",
        "'back' 또는 'menu'를 입력하여 메뉴로 돌아가기",
        "유리수: %d/%d", "p-adic 기수: %d", "변환 실패",
        "=== 식 평가 및 p-adic 변환 (정밀도: 20자리) ===",
        "식과 p 값을 입력하세요 (예: 3+4*2 5)",
        "식: %s", "평가 결과: %d/%d",
        "=== p-adic 변환 테스트 (정밀도: 20자리) ===",
        "=== 유리수 p-adic 변환 테스트 (정밀도: 20자리) ===",
        "테스트%d: 10진수: %d, p-adic 기수: %d",
        "테스트%d: 유리수: %d/%d, p-adic 기수: %d",
        "계산: √(%d/%d)의 %d-adic 표현", "첫 번째 해:", "두 번째 해:",
        "대화 모드로 돌아가기",
        "현재 언어: 한국어",
        "형식 표현: (", "급수 표현: ",
        "형식 표현: (기수가 36 이상이므로 문자 표현 불가, 급수 표현만 표시)",
        "제곱근 결과 (정밀도: %d자리):",
        "계산 중: exp(%d/%d)의 %d-adic",
        "계산 중: log(%d/%d)의 %d-adic",
        "형식 오류. 사용법: exp(x) p",
        "형식 오류. 사용법: log(x) p",
        "exp(x)가 수렴하지 않음: v_p(x) >= 1 필요 (p=2이면 >= 2)",
        "log(x)가 수렴하지 않음: x ≡ 1 (mod p) 필요 (p=2이면 mod 4)",
        "식의 p-adic 변환 실패",
        "exp 결과:",
        "log 결과:",
        "  4. exp(x) p / log(x) p (예: exp(5) 5, log(1+5) 5)",
        "  5. 식 p                (예: 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_FR ==========
    {
        "p-adic> ", "expr> ", "Choix (1-6): ",
        "Appuyez sur Entrée pour revenir au menu...", "Au revoir !", "Choix invalide, veuillez entrer 1-6", "Quitter",
        "Convertisseur p-adic", "==========================",
        "1. Test de l'analyseur syntaxique", "2. Conversion entière p-adic",
        "3. Test de conversion rationnelle p-adic", "4. Conversion p-adic interactive",
        "5. Évaluation d'expression en p-adic", "6. Quitter",
        "Format:",
        "  1. nombre p              (ex: 5 7, 1/3 5)",
        "  2. pow(base, exp) p      (ex: pow(2,1/2) 5)",
        "  3. sqrt(n) p             (ex: sqrt(2) 5)",
        "Commandes: help, quit, exit, menu, language",
        "Erreur de format. Tapez 'help' pour l'aide.",
        "p doit être un entier supérieur à 1", "Erreur d'analyse",
        "Erreur de format. Usage: pow(base, exposant) p",
        "Erreur de format. Usage: sqrt(n) p",
        "Seules les racines carrées sont supportées (exposant doit être 1/2)",
        "Impossible de convertir la base en p-adic", "Pas de racine carrée dans Q_%d",
        "Erreur: utilisez le format 'nombre p' (ex: 17 5 ou 3/4 5)",
        "Erreur: utilisez le format 'expression p' (ex: 3+4*2 5)",
        "Erreur d'analyse de l'expression !",
        "=== Conversion p-adic interactive (précision: 20) ===",
        "  Entier: 17 5  → représentation 5-adique de 17",
        "  Fraction: 3/4 5 → représentation 5-adique de 3/4",
        "Tapez 'back' ou 'menu' pour revenir",
        "Rationnel: %d/%d", "Base p-adique: %d", "Échec de la conversion",
        "=== Évaluation d'expression en p-adic (précision: 20) ===",
        "Entrez une expression et p (ex: 3+4*2 5)",
        "Expression: %s", "Résultat: %d/%d",
        "=== Test de conversion p-adic (précision: 20) ===",
        "=== Test de conversion rationnelle p-adic (précision: 20) ===",
        "Test %d: décimal: %d, base p-adique: %d",
        "Test %d: rationnel: %d/%d, base p-adique: %d",
        "Calcul: √(%d/%d) dans %d-adique", "Première racine:", "Deuxième racine:",
        "Retour au mode interactif",
        "Langue actuelle: Français",
        "Représentation formelle: (", "Représentation en série: ",
        "Représentation formelle: (base >= 36, représentation en série uniquement)",
        "Résultat de la racine carrée (précision: %d chiffres):",
        "Calcul: exp(%d/%d) en %d-adique",
        "Calcul: log(%d/%d) en %d-adique",
        "Erreur de format. Usage: exp(x) p",
        "Erreur de format. Usage: log(x) p",
        "exp(x) ne converge pas : v_p(x) >= 1 requis (>=2 si p=2)",
        "log(x) ne converge pas : x ≡ 1 (mod p) requis (mod 4 si p=2)",
        "Échec de la conversion de l'expression en p-adique",
        "Résultat exp:",
        "Résultat log:",
        "  4. exp(x) p / log(x) p (ex: exp(5) 5, log(1+5) 5)",
        "  5. expression p        (ex: 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_RU ==========
    {
        "p-adic> ", "выражение> ", "Выбор (1-6): ",
        "Нажмите Enter для возврата в меню...", "До свидания!", "Неверный выбор, введите 1-6", "Выход",
        "Конвертер p-adic", "==========================",
        "1. Тест синтаксического анализатора", "2. Преобразование целых чисел в p-adic",
        "3. Тест преобразования рациональных чисел", "4. Интерактивное преобразование p-adic",
        "5. Вычисление выражения в p-adic", "6. Выход",
        "Формат:",
        "  1. число p               (пример: 5 7, 1/3 5)",
        "  2. pow(base, exp) p      (пример: pow(2,1/2) 5)",
        "  3. sqrt(n) p             (пример: sqrt(2) 5)",
        "Команды: help, quit, exit, menu, language",
        "Ошибка формата. Введите 'help' для справки.",
        "p должно быть целым числом больше 1", "Ошибка разбора",
        "Ошибка формата. Использование: pow(base, exponent) p",
        "Ошибка формата. Использование: sqrt(n) p",
        "Поддерживаются только квадратные корни (показатель должен быть 1/2)",
        "Не удалось преобразовать основание в p-adic", "Квадратный корень в Q_%d не существует",
        "Ошибка: используйте формат 'число p' (пример: 17 5 или 3/4 5)",
        "Ошибка: используйте формат 'выражение p' (пример: 3+4*2 5)",
        "Ошибка разбора выражения!",
        "=== Интерактивное преобразование p-adic (точность: 20) ===",
        "  Целое: 17 5  → p-adic представление 17",
        "  Дробь: 3/4 5 → p-adic представление 3/4",
        "Введите 'back' или 'menu' для возврата",
        "Рациональное: %d/%d", "Основание p-adic: %d", "Ошибка преобразования",
        "=== Вычисление выражения в p-adic (точность: 20) ===",
        "Введите выражение и p (пример: 3+4*2 5)",
        "Выражение: %s", "Результат: %d/%d",
        "=== Тест преобразования p-adic (точность: 20) ===",
        "=== Тест преобразования рациональных чисел (точность: 20) ===",
        "Тест %d: десятичное: %d, основание p-adic: %d",
        "Тест %d: рациональное: %d/%d, основание p-adic: %d",
        "Вычисление: √(%d/%d) в %d-adic", "Первый корень:", "Второй корень:",
        "Возврат в интерактивный режим",
        "Текущий язык: Русский",
        "Формальное представление: (", "Представление в виде ряда: ",
        "Формальное представление: (основание >= 36, только ряд)",
        "Результат квадратного корня (точность: %d цифр):",
        "Вычисление: exp(%d/%d) в %d-adic",
        "Вычисление: log(%d/%d) в %d-adic",
        "Ошибка формата. Использование: exp(x) p",
        "Ошибка формата. Использование: log(x) p",
        "exp(x) не сходится: требуется v_p(x) >= 1 (>=2 для p=2)",
        "log(x) не сходится: требуется x ≡ 1 (mod p) (mod 4 для p=2)",
        "Не удалось преобразовать выражение в p-adic",
        "Результат exp:",
        "Результат log:",
        "  4. exp(x) p / log(x) p (пример: exp(5) 5, log(1+5) 5)",
        "  5. выражение p         (пример: 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_ES ==========
    {
        "p-adic> ", "expr> ", "Elección (1-6): ",
        "Presione Enter para volver al menú...", "¡Hasta luego!", "Elección inválida, ingrese 1-6", "Salir",
        "Convertidor p-adic", "==========================",
        "1. Prueba del analizador sintáctico", "2. Conversión entera p-adic",
        "3. Prueba de conversión racional p-adic", "4. Conversión p-adic interactiva",
        "5. Evaluación de expresión a p-adic", "6. Salir",
        "Formato:",
        "  1. número p              (ej: 5 7, 1/3 5)",
        "  2. pow(base, exp) p      (ej: pow(2,1/2) 5)",
        "  3. sqrt(n) p             (ej: sqrt(2) 5)",
        "Comandos: help, quit, exit, menu, language",
        "Error de formato. Escriba 'help' para ayuda.",
        "p debe ser un entero mayor que 1", "Error de análisis",
        "Error de formato. Uso: pow(base, exponente) p",
        "Error de formato. Uso: sqrt(n) p",
        "Solo se admiten raíces cuadradas (el exponente debe ser 1/2)",
        "No se puede convertir la base a p-adic", "No hay raíz cuadrada en Q_%d",
        "Error: use el formato 'número p' (ej: 17 5 o 3/4 5)",
        "Error: use el formato 'expresión p' (ej: 3+4*2 5)",
        "¡Error al analizar la expresión!",
        "=== Conversión p-adic interactiva (precisión: 20) ===",
        "  Entero: 17 5  → representación 5-ádica de 17",
        "  Fracción: 3/4 5 → representación 5-ádica de 3/4",
        "Escriba 'back' o 'menu' para volver",
        "Racional: %d/%d", "Base p-ádica: %d", "Error de conversión",
        "=== Evaluación de expresión a p-adic (precisión: 20) ===",
        "Ingrese expresión y p (ej: 3+4*2 5)",
        "Expresión: %s", "Resultado: %d/%d",
        "=== Prueba de conversión p-adic (precisión: 20) ===",
        "=== Prueba de conversión racional p-adic (precisión: 20) ===",
        "Prueba %d: decimal: %d, base p-ádica: %d",
        "Prueba %d: racional: %d/%d, base p-ádica: %d",
        "Calculando: √(%d/%d) en %d-adic", "Primera raíz:", "Segunda raíz:",
        "Volviendo al modo interactivo",
        "Idioma actual: Español",
        "Representación formal: (", "Representación en serie: ",
        "Representación formal: (base >= 36, solo serie)",
        "Resultado de raíz cuadrada (precisión: %d dígitos):",
        "Calculando: exp(%d/%d) en %d-ádico",
        "Calculando: log(%d/%d) en %d-ádico",
        "Error de formato. Uso: exp(x) p",
        "Error de formato. Uso: log(x) p",
        "exp(x) no converge: se requiere v_p(x) >= 1 (>=2 si p=2)",
        "log(x) no converge: se requiere x ≡ 1 (mod p) (mod 4 si p=2)",
        "Error al convertir la expresión a p-ádico",
        "Resultado exp:",
        "Resultado log:",
        "  4. exp(x) p / log(x) p (ej: exp(5) 5, log(1+5) 5)",
        "  5. expresión p         (ej: 3+4*2 5, (1/3+1)*2 5)",
    },

    // ========== LANG_DE ==========
    {
        "p-adic> ", "Ausdruck> ", "Auswahl (1-6): ",
        "Enter drücken um zum Menü zurückzukehren...", "Auf Wiedersehen!", "Ungültige Auswahl, bitte 1-6 eingeben", "Beenden",
        "p-adic Konverter", "==========================",
        "1. Syntaxanalyse-Test", "2. Ganzzahl p-adic Konvertierung",
        "3. Rationaler p-adic Konvertierungstest", "4. Interaktive p-adic Konvertierung",
        "5. Ausdrucksauswertung zu p-adic", "6. Beenden",
        "Format:",
        "  1. Zahl p                (Bsp: 5 7, 1/3 5)",
        "  2. pow(base, exp) p      (Bsp: pow(2,1/2) 5)",
        "  3. sqrt(n) p             (Bsp: sqrt(2) 5)",
        "Befehle: help, quit, exit, menu, language",
        "Formatfehler. Geben Sie 'help' für Hilfe ein.",
        "p muss eine ganze Zahl größer als 1 sein", "Analysefehler",
        "Formatfehler. Verwendung: pow(base, exponent) p",
        "Formatfehler. Verwendung: sqrt(n) p",
        "Nur Quadratwurzeln werden unterstützt (Exponent muss 1/2 sein)",
        "Basis kann nicht in p-adic umgewandelt werden", "Keine Quadratwurzel in Q_%d",
        "Fehler: Format 'Zahl p' verwenden (Bsp: 17 5 oder 3/4 5)",
        "Fehler: Format 'Ausdruck p' verwenden (Bsp: 3+4*2 5)",
        "Fehler bei der Ausdrucksanalyse!",
        "=== Interaktive p-adic Konvertierung (Genauigkeit: 20) ===",
        "  Ganzzahl: 17 5  → 5-adische Darstellung von 17",
        "  Bruch: 3/4 5    → 5-adische Darstellung von 3/4",
        "'back' oder 'menu' eingeben um zurückzukehren",
        "Rational: %d/%d", "p-adische Basis: %d", "Konvertierung fehlgeschlagen",
        "=== Ausdrucksauswertung zu p-adic (Genauigkeit: 20) ===",
        "Ausdruck und p eingeben (Bsp: 3+4*2 5)",
        "Ausdruck: %s", "Ergebnis: %d/%d",
        "=== p-adic Konvertierungstest (Genauigkeit: 20) ===",
        "=== Rationaler p-adic Konvertierungstest (Genauigkeit: 20) ===",
        "Test %d: Dezimal: %d, p-adische Basis: %d",
        "Test %d: Rational: %d/%d, p-adische Basis: %d",
        "Berechnung: √(%d/%d) in %d-adic", "Erste Wurzel:", "Zweite Wurzel:",
        "Zurück zum interaktiven Modus",
        "Aktuelle Sprache: Deutsch",
        "Formale Darstellung: (", "Reihendarstellung: ",
        "Formale Darstellung: (Basis >= 36, nur Reihendarstellung)",
        "Quadratwurzel-Ergebnis (Genauigkeit: %d Stellen):",
        "Berechne: exp(%d/%d) in %d-adisch",
        "Berechne: log(%d/%d) in %d-adisch",
        "Formatfehler. Verwendung: exp(x) p",
        "Formatfehler. Verwendung: log(x) p",
        "exp(x) konvergiert nicht: v_p(x) >= 1 erforderlich (>=2 bei p=2)",
        "log(x) konvergiert nicht: x ≡ 1 (mod p) erforderlich (mod 4 bei p=2)",
        "Fehler beim Konvertieren des Ausdrucks in p-adisch",
        "exp-Ergebnis:",
        "log-Ergebnis:",
        "  4. exp(x) p / log(x) p (Bsp: exp(5) 5, log(1+5) 5)",
        "  5. Ausdruck p          (Bsp: 3+4*2 5, (1/3+1)*2 5)",
    },
};

void lang_init() {
    char config_path[512];
    const char* home = getenv("HOME");
    if (home == NULL) { current_lang = LANG_ZH_CN; return; }

    snprintf(config_path, sizeof(config_path), "%s/.padic_config", home);

    FILE* f = fopen(config_path, "r");
    if (f == NULL) { current_lang = LANG_ZH_CN; return; }

    char line[64];
    while (fgets(line, sizeof(line), f)) {
        char key[32], value[32];
        if (sscanf(line, "%[^=]=%s", key, value) == 2) {
            if (strcmp(key, "LANG") == 0) {
                if      (strcmp(value, "en")    == 0) current_lang = LANG_EN;
                else if (strcmp(value, "zh_CN") == 0) current_lang = LANG_ZH_CN;
                else if (strcmp(value, "zh_TW") == 0) current_lang = LANG_ZH_TW;
                else if (strcmp(value, "ja")    == 0) current_lang = LANG_JA;
                else if (strcmp(value, "ko")    == 0) current_lang = LANG_KO;
                else if (strcmp(value, "fr")    == 0) current_lang = LANG_FR;
                else if (strcmp(value, "ru")    == 0) current_lang = LANG_RU;
                else if (strcmp(value, "es")    == 0) current_lang = LANG_ES;
                else if (strcmp(value, "de")    == 0) current_lang = LANG_DE;
                else current_lang = LANG_ZH_CN;
                break;
            }
        }
    }
    fclose(f);
}

const char* lang_get(StrIndex index) {
    if (index < 0 || index >= STR_COUNT) return "";
    return strings[current_lang][index];
}

LangCode lang_current() {
    return current_lang;
}
